controller_manager:
  ros__parameters:
    update_rate: 30 # Hz
    use_sim_time: true

    # define controllers
    diff_cont:
      # fija el tipo de controller que se usa existente
      type: diff_drive_controller/DiffDriveController

    # Este no hace nada 
    # \robot_state_publisher necesita de \joint_state topic
    # de forma que se puedan hacer las transformaciones de forma correcta
    joint_broad: 
      type: joint_state_broadcaster/JointStateBroadcaster

    pos_cont: 
      type: position_controllers/JointGroupPositionController

    vel_cont: 
      type: velocity_controllers/JointGroupVelocityController

# Parámetros del control diferencial
diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    # las joints usadas
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.297
    wheel_radius: 0.033

    use_stamped_vel: false

# Parámetros del control por posición
pos_cont:
  ros__parameters:
    # las joints usadas
    joints: ['camera_joint']  
    publish_rate: 50.0

