controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    # define controllers
    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad: # muestra el estado de las joints
      type: joint_state_broadcaster/JointStateBroadcaster

    pos_cont: 
      type: position_controllers/JointGroupPositionController


    vel_cont: 
      type: velocity_controllers/JointGroupVelocityController

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.297
    wheel_radius: 0.033

    use_stamped_vel: false

pos_cont:
  ros__parameters:
    joints: ['camera_joint']  # Aquí debes especificar las joints
    publish_rate: 50.0

