<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!--xacro:include filename="inertial_macros.xacro"/-->


    <!--xacro:property name="chassis_length" value="0.335"/>
    <xacro:property name="chassis_width" value="0.265"/>
    <xacro:property name="chassis_height" value="0.138"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.033"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/-->

    <xacro:property name="wheelSeparation" value="0.13"/>
    <xacro:property name="wheelDiameter" value="0.07"/>
    <xacro:property name="wheelThickness" value="0.024"/>
    <xacro:property name="base_elevation" value="0.01"/>


    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <!--origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/-->
        <origin xyz="0 0 ${base_elevation}" rpy="0 0 0"/>

    </joint>

    <link name="chassis">
        <!--visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box-->

        <visual>
            <!--origin xyz="-0.033 0.0 0.04" rpy="0 0 ${PI}"/-->
            <origin xyz="-0.17 -0.055 0.04" rpy="${-pi/2} 0 0"/>
            <geometry>
            <!--mesh filename="package://${package_name}/meshes/base_plate.stl" scale="1 1 1"/-->
                <mesh filename="package://pibotj_r2c/meshes/base.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="Blue"> <!-- Color in Rviz2 (inside visual tag) -->
                <color rgba="${0/255} ${0/255} ${255/255} 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="-0.17 0 0.04" rpy="0 0 0"/>
            <geometry>
                <box size="0.2 0.1 0.01"/>
            </geometry>
        </collision>
        <!-- Collision tag added to stabilize the robot -->
        <collision> 
            <origin xyz="0.06 0 0.002" rpy="0 0 0" />
             <geometry>
            <sphere radius="0.01" />
         </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${wheelDiameter-base_elevation}" rpy="0 0 0"/>
            <mass value="100"/>
            <inertia ixx="0.333333" ixy="0.0" ixz="0.0"  iyy="0.333333" iyz="0.0"  izz="0.6" />
         </inertial>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <!--origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" /-->
        <origin xyz="0 ${wheelSeparation/2} ${wheelDiameter/2-base_elevation}" rpy="${-pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <!--visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder-->

        <visual>
            <origin xyz="0 0 0.015" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://pibotj_r2c/meshes/wheel_ring.stl" scale="1 1 1"/>
            </geometry>
            <material name="white"/> <!-- Color in Rviz2 (inside visual tag) -->
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <cylinder length="${wheelThickness}" radius="${wheelDiameter/2}"/>
        </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="5" />
            <inertia ixx="0.0135417" ixy="0.0" ixz="0.0"  iyy="0.0135417" iyz="0.0"  izz="0.025" />
            </inertial>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>




    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <!--origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" /-->
        <origin xyz="0 ${-wheelSeparation/2} ${wheelDiameter/2-base_elevation}" rpy="${-pi/2} 0 0"/>
        <!--axis xyz="0 0 -1"/-->
        <axis xyz="0 0 1"/>

    </joint>

    <link name="right_wheel">
        <!--visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder-->

        <visual>
            <origin xyz="0 0 -0.015" rpy="${pi} 0 0"/> <!-- -z and r=PI for the other wheel -->
            <geometry>
                <mesh filename="package://pibotj_r2c/meshes/wheel_ring.stl" scale="1 1 1"/>
            </geometry>
            <material name="white"/> <!-- Color in Rviz2 (inside visual tag) -->
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheelThickness}" radius="${wheelDiameter/2}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="5" />
            <inertia ixx="0.0135417" ixy="0.0" ixz="0.0"  iyy="0.0135417" iyz="0.0"  izz="0.025" />
        </inertial>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>


    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <!--origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/-->
        <origin xyz="-0.135 -0.01 0.006" rpy="0 ${pi} ${pi}" />

    </joint>


    <link name="caster_wheel">
        <!--visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere-->

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://pibotj_r2c/meshes/bolaloca.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <!--cylinder length="0.01" radius="0.015" /-->
                <box size="0.01 0.1 0.03"/> 
            </geometry>
        </collision>
        <inertial>
            <origin xyz="6.93889390390723E-18 -2.62037475051713E-11 -2.77710070911708E-09" rpy="0 0 0" />
            <mass value="0.08" />
            <inertia ixx="0.0004" ixy="0" ixz="0" iyy="0.0004" iyz="0" izz="0.00001" />
        </inertial>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>