<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="wheelSeparation" value="0.13"/>
    <xacro:property name="wheelDiameter" value="0.07"/>
    <xacro:property name="wheelThickness" value="0.024"/>
    <xacro:property name="base_elevation" value="0.005"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${base_elevation}" rpy="0 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="-0.17 -0.055 0.04" rpy="${-pi/2} 0 0"/>
            <geometry>
                <mesh filename="package://pibotj_r2c/meshes/base.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="Blue"> <!-- Color in Rviz2 (inside visual tag) -->
                <color rgba="${0/255} ${0/255} ${255/255} 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="-0.17 0 0.04" rpy="0 0 0"/>
            <geometry>
                <box size="0.2 0.1 0.01"/>
            </geometry>
        </collision>
        <!-- Collision tag added to stabilize the robot -->
        <collision> 
            <origin xyz="0.06 0 0.002" rpy="0 0 0" />
             <geometry>
            <sphere radius="0.01" />
         </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${wheelDiameter-base_elevation}" rpy="0 0 0"/>
            <mass value="100"/>
            <inertia ixx="3.375" ixy="0.0" ixz="0.0" iyy="0.808" iyz="0.0" izz="2.833" />
         </inertial>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheelSeparation/2} ${wheelDiameter/2-base_elevation}" rpy="${-pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <origin xyz="0 0 0.015" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://pibotj_r2c/meshes/wheel_ring.stl" scale="0.9 0.9 0.9"/>
            </geometry>
            <material name="white"/> <!-- Color in Rviz2 (inside visual tag) -->
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <cylinder length="${wheelThickness}" radius="${wheelDiameter/2}"/>
        </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="5" />
            <inertia ixx="0.0135417" ixy="0.0" ixz="0.0"  iyy="0.0135417" iyz="0.0"  izz="0.025" />
            </inertial>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheelSeparation/2} ${wheelDiameter/2-base_elevation}" rpy="${-pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <origin xyz="0 0 -0.015" rpy="${pi} 0 0"/> <!-- -z and r=PI for the other wheel -->
            <geometry>
                <mesh filename="package://pibotj_r2c/meshes/wheel_ring.stl" scale="0.9 0.9 0.9"/>
            </geometry>
            <material name="white"/> <!-- Color en Rviz2-->
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheelThickness}" radius="${wheelDiameter/2}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="5" />
            <inertia ixx="0.0135417" ixy="0.0" ixz="0.0"  iyy="0.0135417" iyz="0.0"  izz="0.025" />
        </inertial>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="-0.135 -0.01 0.006" rpy="0 ${pi} ${pi}" />
    </joint>

    <link name="caster_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://pibotj_r2c/meshes/bolaloca.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.01 0.1 0.03"/> 
            </geometry>
        </collision>
        <inertial>
            <origin xyz="6.93889390390723E-18 -2.62037475051713E-11 -2.77710070911708E-09" rpy="0 0 0" />
            <mass value="10.0" />
            <inertia ixx="0.0006" ixy="0" ixz="0" iyy="0.0006" iyz="0" izz="0.00002" /> 
        </inertial>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>